name: disable workflow

on:
  push:
    branches: [main]
jobs:
    disable:
         runs-on: ubuntu-latest
        
         steps:
           - name: wk
             run: echo "disable the workflow"
           
    
